### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by DekaSKy** [zivyuan/aw-minions#1]
Hello,how install this project?

**Comment by zivyuan** [comment]
If you familiar with nodejs, just download the code and then run `npm install`.
After install you can run `node main.js ` to launch this project

**Comment by zivyuan** [comment]
> If you familiar with nodejs, just download the code and then run `npm install`. After install you can run `node main.js ` to launch this project

Missing build script, run `npm run build` to build before start.
